=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act4/futbol.dtd
<!ELEMENT competicion (equipos+)>
<!ATTLIST competicion anyo CDATA #IMPLIED>

<!ELEMENT equipos (nombre_equipo,nacionalidad,presupuesto?,(normal|doble),sweepers,pista,fecha_fundacion)>
<!ELEMENT nombre_equipo (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT presupuesto (#PCDATA)>

<!ELEMENT normal EMPTY>
<!ELEMENT doble EMPTY>

<!ELEMENT sweepers (sweeper+)>
<!ELEMENT sweeper (nombre,apellidos,edad,sexo)>
<!ATTLIST sweeper dni CDATA #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>

<!ELEMENT pista (nombre_pista,asientos,direccion)>
<!ELEMENT nombre_pista (#PCDATA)>
<!ELEMENT asientos (#PCDATA)>

<!ELEMENT direccion (calle,numero,poblacion)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT poblacion (cp?,provincia)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>

<!ELEMENT fecha_fundacion (dia,mes,anyo)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anyo (#PCDATA)>

=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act4/futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE competicion SYSTEM "futbol.dtd">
<competicion anyo="2025">
    <equipos>
      <nombre_equipo></nombre_equipo>
      <nacionalidad></nacionalidad>
      <presupuesto></presupuesto>
      <normal/>
      <sweepers>
        <sweeper dni="M43568723">
          <nombre></nombre>
          <apellidos></apellidos>
          <edad></edad>
          <sexo></sexo>
        </sweeper>
        <sweeper dni="L93569723">
          <nombre></nombre>
          <apellidos></apellidos>
          <edad></edad>
          <sexo></sexo>
        </sweeper>
      </sweepers>
      <pista>
        <nombre_pista></nombre_pista>
        <asientos></asientos>
        <direccion>
          <calle></calle>
          <numero></numero>
          <poblacion>
            <cp></cp>
            <provincia></provincia>
          </poblacion>
        </direccion>
      </pista>
      <fecha_fundacion>
        <dia></dia>
        <mes></mes>
        <anyo></anyo>
      </fecha_fundacion>
    </equipos>
    <!--EQUIPO 2-->
    <equipos>
      <nombre_equipo></nombre_equipo>
      <nacionalidad></nacionalidad>
      <presupuesto></presupuesto>
      <normal/>
      <sweepers>
        <sweeper dni="M43558723">
          <nombre></nombre>
          <apellidos></apellidos>
          <edad></edad>
          <sexo></sexo>
        </sweeper>
        <sweeper dni="L94569723">
          <nombre></nombre>
          <apellidos></apellidos>
          <edad></edad>
          <sexo></sexo>
        </sweeper>
      </sweepers>
      <pista>
        <nombre_pista></nombre_pista>
        <asientos></asientos>
        <direccion>
          <calle></calle>
          <numero></numero>
          <poblacion>
            <cp></cp>
            <provincia></provincia>
          </poblacion>
        </direccion>
      </pista>
      <fecha_fundacion>
        <dia></dia>
        <mes></mes>
        <anyo></anyo>
      </fecha_fundacion>
    </equipos>
</competicion>
