=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act5/colegio.dtd
<!ELEMENT escuela (cursos)>
<!ELEMENT cursos (curso+)>
<!ELEMENT curso (nombre_curso,duracion,descripcion,(becas|nobecas),aula,precio,semanas,profesores,temas)>
<!ATTLIST curso identificador ID #REQUIRED>

<!ELEMENT nombre_curso (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT becas EMPTY>
<!ELEMENT nobecas EMPTY>

<!ELEMENT aula (num_planta,num_aula)>
<!ATTLIST aula informatica (si | no) #REQUIRED>
<!ELEMENT num_planta (#PCDATA)>
<!ELEMENT num_aula (#PCDATA)>

<!ELEMENT precio (antiguos_alumnos,nuevos_alumnos)>
<!ELEMENT antiguos_alumnos (#PCDATA)>
<!ELEMENT nuevos_alumnos (#PCDATA)>

<!ELEMENT semanas (semana+)>
<!ELEMENT semana (inicio,fin)>
<!ATTLIST semana horario (manana | tarde) #REQUIRED>

<!ELEMENT inicio (dia,mes,agno)>
<!ELEMENT fin (dia,mes,agno)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT agno (#PCDATA)>

<!ELEMENT profesores (profesor+)>
<!ELEMENT profesor (nombre,apellidos)>
<!ATTLIST profesor tipo (practica | teoria) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT temas (tema+)>
<!ELEMENT tema (titulo,resumen,palabras_clave,ejercicios)>
<!ATTLIST tema numero ID #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT palabras_clave (#PCDATA)>

<!ELEMENT ejercicios (practicos,teoricos)*>

<!ELEMENT practicos (num_ejercicios_practicos,duracion_ejercicio_practico)>
<!ELEMENT num_ejercicios_practicos (#PCDATA)>
<!ELEMENT duracion_ejercicio_practico (#PCDATA)>

<!ELEMENT teoricos (num_ejercicios_teoricos,duracion_ejercicio_teorico)>
<!ELEMENT num_ejercicios_teoricos (#PCDATA)>
<!ELEMENT duracion_ejercicio_teorico (#PCDATA)>

=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act5/colegio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escuela SYSTEM "colegio.dtd">
<escuela>
    <cursos>
      <curso identificador="a1">
        <nombre_curso></nombre_curso>
        <duracion></duracion>
        <descripcion></descripcion>
        <becas />
        <aula informatica="si">
          <num_planta></num_planta>
          <num_aula></num_aula>
        </aula>
        <precio>
          <antiguos_alumnos></antiguos_alumnos>
          <nuevos_alumnos></nuevos_alumnos>
        </precio>
        <semanas>
          <semana horario="manana">
            <inicio>
              <dia>01</dia>
              <mes>01</mes>
              <agno>2025</agno>
            </inicio>
            <fin>
              <dia>31</dia>
              <mes>01</mes>
              <agno>2025</agno>
            </fin>
          </semana>
          <semana horario="tarde">
            <inicio>
              <dia>01</dia>
              <mes>02</mes>
              <agno>2025</agno>
            </inicio>
            <fin>
              <dia>28</dia>
              <mes>02</mes>
              <agno>2025</agno>
            </fin>
          </semana>
          <semana horario="tarde">
            <inicio>
              <dia>01</dia>
              <mes>03</mes>
              <agno>2025</agno>
            </inicio>
            <fin>
              <dia>31</dia>
              <mes>03</mes>
              <agno>2025</agno>
            </fin>
          </semana>
        </semanas>
        <profesores>
          <profesor tipo="practica">
            <nombre></nombre>
            <apellidos></apellidos>
          </profesor>
          <profesor tipo="teoria">
            <nombre></nombre>
            <apellidos></apellidos>
          </profesor>
        </profesores>
        <temas>
          <tema numero="t1">
            <titulo></titulo>
            <resumen></resumen>
            <palabras_clave></palabras_clave>
            <ejercicios>
              <practicos>
                <num_ejercicios_practicos></num_ejercicios_practicos>
                <duracion_ejercicio_practico></duracion_ejercicio_practico>
              </practicos>
              <teoricos>
                <num_ejercicios_teoricos></num_ejercicios_teoricos>
                <duracion_ejercicio_teorico></duracion_ejercicio_teorico>
              </teoricos>
            </ejercicios>
          </tema>
          <tema numero="t2">
            <titulo></titulo>
            <resumen></resumen>
            <palabras_clave></palabras_clave>
            <ejercicios>
              <practicos>
                <num_ejercicios_practicos></num_ejercicios_practicos>
                <duracion_ejercicio_practico></duracion_ejercicio_practico>
              </practicos>
              <teoricos>
                <num_ejercicios_teoricos></num_ejercicios_teoricos>
                <duracion_ejercicio_teorico></duracion_ejercicio_teorico>
              </teoricos>
            </ejercicios>
          </tema>
        </temas>
      </curso>
      <curso identificador="a2">
        <nombre_curso></nombre_curso>
        <duracion></duracion>
        <descripcion></descripcion>
        <nobecas />
        <aula informatica="no">
          <num_planta></num_planta>
          <num_aula></num_aula>
        </aula>
        <precio>
          <antiguos_alumnos></antiguos_alumnos>
          <nuevos_alumnos></nuevos_alumnos>
        </precio>
        <semanas>
          <semana horario="manana">
            <inicio>
              <dia>01</dia>
              <mes>01</mes>
              <agno>2025</agno>
            </inicio>
            <fin>
              <dia>31</dia>
              <mes>01</mes>
              <agno>2025</agno>
            </fin>
          </semana>
          <semana horario="tarde">
            <inicio>
              <dia>01</dia>
              <mes>02</mes>
              <agno>2025</agno>
            </inicio>
            <fin>
              <dia>28</dia>
              <mes>02</mes>
              <agno>2025</agno>
            </fin>
          </semana>
          <semana horario="tarde">
            <inicio>
              <dia>01</dia>
              <mes>03</mes>
              <agno>2025</agno>
            </inicio>
            <fin>
              <dia>31</dia>
              <mes>03</mes>
              <agno>2025</agno>
            </fin>
          </semana>
        </semanas>
        <profesores>
          <profesor tipo="practica">
            <nombre></nombre>
            <apellidos></apellidos>
          </profesor>
          <profesor tipo="teoria">
            <nombre></nombre>
            <apellidos></apellidos>
          </profesor>
        </profesores>
        <temas>
          <tema numero="t3">
            <titulo></titulo>
            <resumen></resumen>
            <palabras_clave></palabras_clave>
            <ejercicios>
              <practicos>
                <num_ejercicios_practicos></num_ejercicios_practicos>
                <duracion_ejercicio_practico></duracion_ejercicio_practico>
              </practicos>
              <teoricos>
                <num_ejercicios_teoricos></num_ejercicios_teoricos>
                <duracion_ejercicio_teorico></duracion_ejercicio_teorico>
              </teoricos>
            </ejercicios>
          </tema>
          <tema numero="t4">
            <titulo></titulo>
            <resumen></resumen>
            <palabras_clave></palabras_clave>
            <ejercicios>
              <practicos>
                <num_ejercicios_practicos></num_ejercicios_practicos>
                <duracion_ejercicio_practico></duracion_ejercicio_practico>
              </practicos>
              <teoricos>
                <num_ejercicios_teoricos></num_ejercicios_teoricos>
                <duracion_ejercicio_teorico></duracion_ejercicio_teorico>
              </teoricos>
            </ejercicios>
          </tema>
        </temas>
      </curso>
    </cursos>
</escuela>
