=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act3/cine.dtd
<!ELEMENT cartelera (pelicula+)>

<!ELEMENT pelicula (titulo, nacionalidad, duracion, director, actores, descripcion)>
<!ATTLIST pelicula estreno CDATA #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT director (#PCDATA)>

<!ELEMENT actores (actor+)>

<!ELEMENT actor (nombre, apellidos)>
<!ATTLIST actor tipo (principal | reparto) #IMPLIED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>

<!ELEMENT descripcion (#PCDATA)>

=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act3/cine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cartelera SYSTEM "cine.dtd">
<cartelera>
    <pelicula estreno="2025">
      <titulo>Pelicula 1</titulo>
      <nacionalidad></nacionalidad>
      <duracion></duracion>
      <director></director>
      <actores>
        <actor tipo="principal">
          <nombre></nombre>
          <apellidos></apellidos>
        </actor>
        <actor tipo="reparto">
          <nombre></nombre>
          <apellidos></apellidos>
        </actor>
      </actores>
      <descripcion></descripcion>
    </pelicula>
    <pelicula estreno="2027">
      <titulo>Pelicula 2</titulo>
      <nacionalidad></nacionalidad>
      <duracion></duracion>
      <director></director>
      <actores>
        <actor tipo="principal">
          <nombre></nombre>
          <apellidos></apellidos>
        </actor>
        <actor tipo="reparto">
          <nombre></nombre>
          <apellidos></apellidos>
        </actor>
      </actores>
      <descripcion></descripcion>
    </pelicula>
</cartelera>
