=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act6/tv.dtd
<!ELEMENT TVSCHEDULE (CHANNEL+)>
<!ELEMENT CHANNEL (BANNER,DAY+)>
<!ELEMENT BANNER (#PCDATA)>
<!ELEMENT DAY (DATE, (HOLIDAY | PROGRAMSLOT+)+)>
<!ELEMENT HOLIDAY (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT PROGRAMSLOT (TIME, TITLE,DESCRIPTION?)>
<!ELEMENT TIME (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>

<!ATTLIST TVSCHEDULE NAME CDATA #REQUIRED>
<!ATTLIST CHANNEL CHAN CDATA #REQUIRED>
<!ATTLIST PROGRAMSLOT VTR CDATA #IMPLIED>
<!ATTLIST TITLE RATING CDATA #IMPLIED>
<!ATTLIST TITLE LANGUAGE CDATA #IMPLIED>

=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act6/miTV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TVSCHEDULE SYSTEM "tv.dtd">
<TVSCHEDULE NAME="nombre">
    <CHANNEL CHAN="canal">
      <BANNER></BANNER>
      <DAY>
        <DATE></DATE>
        <HOLIDAY></HOLIDAY>
        <PROGRAMSLOT VTR="dato1">
          <TIME></TIME>
          <TITLE></TITLE>
          <DESCRIPTION></DESCRIPTION>
        </PROGRAMSLOT>
        <PROGRAMSLOT VTR="dato2">
          <TIME></TIME>
          <TITLE RATING="clasificacion" LANGUAGE="idioma"></TITLE>
        </PROGRAMSLOT>
        <HOLIDAY></HOLIDAY>
      </DAY>
      <DAY>
        <DATE></DATE>
        <HOLIDAY></HOLIDAY>
        <PROGRAMSLOT VTR="dato3">
          <TIME></TIME>
          <TITLE></TITLE>
          <DESCRIPTION></DESCRIPTION>
        </PROGRAMSLOT>
        <PROGRAMSLOT VTR="dato4">
          <TIME></TIME>
          <TITLE RATING="clasificacion2" LANGUAGE="idioma2"></TITLE>
        </PROGRAMSLOT>
        <HOLIDAY></HOLIDAY>
      </DAY>
    </CHANNEL>
</TVSCHEDULE>
