=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act2/escuela.dtd
<!ELEMENT aula (alumno+)>

<!ELEMENT alumno (nombre,apellidos,sexo,fecha_nacimiento,direccion,telefono,nota_ciclo)>
<!ATTLIST alumno dni ID #REQUIRED>

<!ELEMENT nombre (#PCDATA) >
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>

<!ELEMENT fecha_nacimiento (dia,mes,agno)>
<!ATTLIST fecha_nacimiento zodiaco (leo|tauro) #IMPLIED>


<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT agno (#PCDATA)>

<!ELEMENT direccion (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (fijo | movil)  #IMPLIED>

<!ELEMENT nota_ciclo (#PCDATA)>

=== MariaMalaver/Lenguaje-de-marca/relaciones1_2/relacion2/act2/escuela.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aula SYSTEM "escuela.dtd">
<aula>
    <alumno dni="D54168465">
      <nombre></nombre>
      <apellidos></apellidos>
      <sexo></sexo>
      <fecha_nacimiento zodiaco="leo">
        <dia></dia>
        <mes></mes>
        <agno></agno>
      </fecha_nacimiento>
      <direccion></direccion>
      <telefono tipo="fijo"></telefono>
      <nota_ciclo></nota_ciclo>
    </alumno>
    <alumno dni="R87653456">
      <nombre></nombre>
      <apellidos></apellidos>
      <sexo></sexo>
      <fecha_nacimiento zodiaco="leo">
        <dia></dia>
        <mes></mes>
        <agno></agno>
      </fecha_nacimiento>
      <direccion></direccion>
      <telefono tipo="fijo"></telefono>
      <nota_ciclo></nota_ciclo>
    </alumno>
</aula>
